### ISSUE TITLE
fix your MINS... plz... what a headache. 

### ISSUE THREAD

**Issue by tbillion** [janelia-arduino/Streaming#20]
In file included from c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\bits\stl_algo.h:60,
                 from c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\functional:65,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\Updater\src/Updater.h:25,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/BearSSLHelpers.h:27,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecureBearSSL.h:29,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecure.h:24,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFi.h:11,
                 from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:33:
c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\bits\algorithmfwd.h:425:41: error: macro "min" passed 3 arguments, but takes just 2
  425 |     min(const _Tp&, const _Tp&, _Compare);
      |                                         ^
In file included from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:31:
c:\Users\LocalAdmin\Documents\libraries\Streaming\src/Streaming.h:74: note: macro "min" defined here
   74 | #define min(a,b) ((a)<(b)?(a):(b))
      | 
In file included from c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\bits\stl_algo.h:60,
                 from c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\functional:65,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\Updater\src/Updater.h:25,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/BearSSLHelpers.h:27,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecureBearSSL.h:29,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecure.h:24,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFi.h:11,
                 from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:33:
c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\bits\algorithmfwd.h:453:30: error: macro "min" requires 2 arguments, but only 1 given
  453 |     min(initializer_list<_Tp>);
      |                              ^
In file included from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:31:
c:\Users\LocalAdmin\Documents\libraries\Streaming\src/Streaming.h:74: note: macro "min" defined here
   74 | #define min(a,b) ((a)<(b)?(a):(b))
      | 
In file included from c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\bits\stl_algo.h:66,
                 from c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\functional:65,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\Updater\src/Updater.h:25,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/BearSSLHelpers.h:27,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecureBearSSL.h:29,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecure.h:24,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFi.h:11,
                 from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:33:
c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\bits\uniform_int_dist.h:173:11: error: macro "min" requires 2 arguments, but only 1 given
  173 |       min() const
      |           ^
In file included from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:31:
c:\Users\LocalAdmin\Documents\libraries\Streaming\src/Streaming.h:74: note: macro "min" defined here
   74 | #define min(a,b) ((a)<(b)?(a):(b))
      | 
In file included from c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\bits\stl_algo.h:66,
                 from c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\functional:65,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\Updater\src/Updater.h:25,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/BearSSLHelpers.h:27,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecureBearSSL.h:29,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecure.h:24,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFi.h:11,
                 from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:33:
c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\bits\uniform_int_dist.h:251:40: error: macro "min" requires 2 arguments, but only 1 given
  251 |  const __uctype __urngmin = __urng.min();
      |                                        ^
In file included from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:31:
c:\Users\LocalAdmin\Documents\libraries\Streaming\src/Streaming.h:74: note: macro "min" defined here
   74 | #define min(a,b) ((a)<(b)?(a):(b))
      | 
In file included from c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\bits\stl_algo.h:66,
                 from c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\functional:65,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\Updater\src/Updater.h:25,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/BearSSLHelpers.h:27,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecureBearSSL.h:29,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecure.h:24,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFi.h:11,
                 from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:33:
c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\bits\uniform_int_dist.h:320:40: error: macro "min" requires 2 arguments, but only 1 given
  320 |  const __uctype __urngmin = __urng.min();
      |                                        ^
In file included from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:31:
c:\Users\LocalAdmin\Documents\libraries\Streaming\src/Streaming.h:74: note: macro "min" defined here
   74 | #define min(a,b) ((a)<(b)?(a):(b))
      | 
In file included from c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\functional:65,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\Updater\src/Updater.h:25,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/BearSSLHelpers.h:27,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecureBearSSL.h:29,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecure.h:24,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFi.h:11,
                 from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:33:
c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\bits\stl_algo.h:3473:34: error: macro "min" requires 2 arguments, but only 1 given
 3473 |     min(initializer_list<_Tp> __l)
      |                                  ^
In file included from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:31:
c:\Users\LocalAdmin\Documents\libraries\Streaming\src/Streaming.h:74: note: macro "min" defined here
   74 | #define min(a,b) ((a)<(b)?(a):(b))
      | 
In file included from c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\functional:65,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\Updater\src/Updater.h:25,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/BearSSLHelpers.h:27,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecureBearSSL.h:29,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecure.h:24,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFi.h:11,
                 from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:33:
c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\bits\stl_algo.h:3776:57: error: macro "min" requires 2 arguments, but only 1 given
 3776 |       const __uc_type __urngrange = __g.max() - __g.min();
      |                                                         ^
In file included from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:31:
c:\Users\LocalAdmin\Documents\libraries\Streaming\src/Streaming.h:74: note: macro "min" defined here
   74 | #define min(a,b) ((a)<(b)?(a):(b))
      | 
In file included from c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\functional:65,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\Updater\src/Updater.h:25,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/BearSSLHelpers.h:27,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecureBearSSL.h:29,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFiClientSecure.h:24,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\WiFi\src/WiFi.h:11,
                 from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:33:
c:\users\localadmin\appdata\local\arduino15\packages\rp2040\tools\pqt-gcc\1.4.0-c-0196c06\arm-none-eabi\include\c++\10.3.0\bits\stl_algo.h:5815:57: error: macro "min" requires 2 arguments, but only 1 given
 5815 |       const __uc_type __urngrange = __g.max() - __g.min();
      |                                                         ^
In file included from D:\Arduino\Hypervisor_VisualMenuINTEGRATION\Hypervisor_VisualMenuINTEGRATION.ino:31:
c:\Users\LocalAdmin\Documents\libraries\Streaming\src/Streaming.h:74: note: macro "min" defined here
   74 | #define min(a,b) ((a)<(b)?(a):(b))
      | 
Multiple libraries were found for "SdFat.h"
  Used: C:\Users\LocalAdmin\Documents\libraries\SdFat
  Not used: C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.6.0\libraries\ESP8266SdFat
exit status 1

Compilation error: exit status 1

https://forum.arduino.cc/t/what-is-the-meaning-of-this/1046401

most importantly STREAMING was to blame, rolled it back 3 minor revisions before it was actually able to compile.

**Comment by peterpolidoro** [comment]
Renamed the "min" macro to "STREAMING_MIN" to avoid conflicts.
