### ISSUE TITLE
Printing n decimal places?

### ISSUE THREAD

**Issue by Bwanna** [janelia-arduino/Streaming#21]
Hi,
Is it possible to print a set number of places to the right of the decimal?

In the example: "4"
`Serial.print(1.23456, 4) gives "1.2346"`

**Comment by peterpolidoro** [comment]
Hi,

Yes it is possible to print a set number of places to the right of the decimal using "_FLOAT(double value, int digits)". I added a line demonstrating this in the examples and also in the README.

**Comment by Bwanna** [comment]
Thank you!
