### ISSUE TITLE
Problem with esp8266 StreamDev.h

### ISSUE THREAD

**Issue by thistleshire** [janelia-arduino/Streaming#22]
StreamDev.h defines a minimal set of `operator <<` at https://github.com/esp8266/Arduino/blob/80bf71662551fb5e6579713dc15e541ac48ccf98/cores/esp8266/StreamDev.h#L239-L243 and at https://github.com/esp8266/Arduino/blob/80bf71662551fb5e6579713dc15e541ac48ccf98/cores/esp8266/StreamSend.cpp#L315-L359 - I removed these and now the nicer implementation in this library works just fine.

So might document deleting those lines as workaround to make this work.

**Comment by peterpolidoro** [comment]
It's a shame that there is a conflict, but I will add that to the documentation, thanks!

**Comment by peterpolidoro** [comment]
I added a comment about this in the README. Thanks!
