### ISSUE TITLE
Comma separator for printing multiple variables

### ISSUE THREAD

**Issue by avandalen** [janelia-arduino/Streaming#24]
This is not an issue:
Here is a handy solution that makes it easier to print multiple variables one after the other, using a comma separator. Can this be integrated? I use it a lot..

`#include <Streaming.h>

template<class T> 
inline Print &operator ,(Print &stream, const T arg) 
{ stream.print(" ");
  stream.print(arg); 
  return stream; 
}

int a, b, c, d, e, f;

void setup()
{ Serial.begin(115200);
  Serial << "\nData: " << a, b, c, d, e, f;
  // instead of:
  Serial << "\nData: " << a << " " << b << " " << c << " " << d << " " << e << " " << f <<  endl;
}

void loop()
{  
}`

**Comment by peterpolidoro** [comment]
Very clever! I will definitely add this. It may take a week or two before I have time though. Thank you!

**Comment by peterpolidoro** [comment]
Added. Thanks!
