### ISSUE TITLE
Mimicking  Serial.print(1.23456, 4) gives "1.2346"

### ISSUE THREAD

**Issue by Bwanna** [janelia-arduino/Streaming#4]
Trying to Serial.print a high precision number "double testval= -0.8422240081E-07"
Serial.println(testval, 17); //this displays  “-0.00000008422240081″

Is there a format for Streaming to print the same thing?  
Serial << "testval: \t" << testval << **?????** << endl;

**Comment by Bwanna** [comment]
Discovered the new Version 6 provides this feature in  "_Float(val, format)".
ISSUE CLOSED.

**Comment by Bwanna** [comment]
Discovered the new Version 6 provides this feature in "_Float(val, format)".
ISSUE CLOSED.

**Comment by brand17** [comment]
"_FLOAT(0.123456, 6)" working in my case
